### ISSUE TITLE
Input UX - keyboard repeat and Ctrl key?

### ISSUE THREAD

**Issue by craigcomstock** [asiekierka/uxnds#7]
Playing with https://git.sr.ht/~rabbits/left I notice that keys don't auto-repeat on the uxnds keyboard and that I can't seem to do any control sequences like c-o, c-r or c-s to rename/save a file.

Works great otherwise, just need a pen! :O

**Comment by DeltaF1** [comment]
I agree that auto-repeat would be nice. I don't know if the on-screen keyboard provided by devkitpro has an auto-repeat feature.

For the control sequences, left is kinda cheating and is interpreting holding the (A) button as holding down the control key, because the desktop implementation maps Control to (A). So you can do the control sequences by holding down the A button on the DS and then typing the key. (i.e. hold A and then type s on the on-screen keyboard)

**Comment by craigcomstock** [comment]
Odd. Thanks for the tip. Indeed that works. I'll check out devkitpro maybe. Maybe I can add some debugs and figure out https://github.com/asiekierka/uxnds/issues/6

**Comment by craigcomstock** [comment]
Since the keyboard is from devkitpro I don't see any reason to keep this issue open. Thanks!

**Comment by craigcomstock** [comment]
FWIW, found the keyboard code in libnds here: https://github.com/devkitPro/libnds/blob/master/source/arm9/keyboard.c
